export type YeshivaCategory =
  | 'early-childhood'
  | 'elementary'
  | 'high-school'
  | 'seminary'
  | 'yeshiva-gedolah';

export interface Yeshiva {
  name: string;
  address: string;
  city: string;
  state: string;
  country: string;
  phone?: string;
  fax?: string;
  email?: string;
  website?: string;
  principal?: string;
  director?: string;
  dean?: string;
  founded?: string;
  grades?: string;
  gender?: 'boys' | 'girls' | 'co-ed';
  category: YeshivaCategory;
}

export const categoryLabels: Record<YeshivaCategory, string> = {
  'early-childhood': 'Early Childhood / Preschool',
  'elementary': 'Elementary Schools',
  'high-school': 'High Schools & Mesivtas',
  'seminary': 'Seminaries',
  'yeshiva-gedolah': 'Yeshivos Gedolos',
};

export const yeshivas: Yeshiva[] = [
  // ===== EARLY CHILDHOOD — USA =====
  { name: 'Chabad Early Learning Center', address: 'Birmingham, AL', city: 'Birmingham', state: 'Alabama', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Jewish Preschool', address: 'Anchorage, AK', city: 'Anchorage', state: 'Alaska', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Agoura Hills, CA', city: 'Agoura Hills', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Torah Tots Preschool', address: 'Carlsbad, CA', city: 'Carlsbad', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Contra Costa, CA', city: 'Contra Costa', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Davis, CA', city: 'Davis', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Jewish Preschool', address: 'Folsom, CA', city: 'Folsom', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Irvine, CA', city: 'Irvine', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Hebrew Academy Preschool', address: 'La Jolla, CA', city: 'La Jolla', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Long Beach, CA', city: 'Long Beach', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Marin Children\'s Center', address: 'Marin, CA', city: 'Marin', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Palo Alto, CA', city: 'Palo Alto', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Early Childhood Center', address: 'Rancho Mirage, CA', city: 'Rancho Mirage', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Rancho S. Margarita, CA', city: 'Rancho S. Margarita', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Early Childhood Center', address: 'Sacramento, CA', city: 'Sacramento', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Torah Tots Preschool', address: 'San Diego, CA', city: 'San Diego', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'San Francisco, CA', city: 'San Francisco', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad ECE', address: 'San Jose, CA', city: 'San Jose', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'San Mateo, CA', city: 'San Mateo', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Santa Monica, CA', city: 'Santa Monica', state: 'California', country: 'USA', category: 'early-childhood' },
  { name: 'Friendship Circle Early Childhood', address: 'Denver, CO', city: 'Denver', state: 'Colorado', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Early Childhood Center', address: 'Cheshire, CT', city: 'Cheshire', state: 'Connecticut', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Fairfield, CT', city: 'Fairfield', state: 'Connecticut', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Early Childhood Center', address: 'Greenwich, CT', city: 'Greenwich', state: 'Connecticut', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'New London, CT', city: 'New London', state: 'Connecticut', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Shelton, CT', city: 'Shelton', state: 'Connecticut', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Westport, CT', city: 'Westport', state: 'Connecticut', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Chaya', address: 'Aventura, FL', city: 'Aventura', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Friendship Circle ECE', address: 'Boca Raton, FL', city: 'Boca Raton', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Boynton Beach, FL', city: 'Boynton Beach', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Coral Springs, FL', city: 'Coral Springs', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Lubavitch Chabad Nursery', address: 'Fort Lauderdale, FL', city: 'Fort Lauderdale', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Fort Myers, FL', city: 'Fort Myers', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Jupiter, FL', city: 'Jupiter', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Early Childhood Center', address: 'Orlando, FL', city: 'Orlando', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Torah Tots Academy', address: 'Palm Beach Gardens, FL', city: 'Palm Beach Gardens', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Parkland, FL', city: 'Parkland', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Pembroke Pines, FL', city: 'Pembroke Pines', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Plantation, FL', city: 'Plantation', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Sarasota, FL', city: 'Sarasota', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Weston, FL', city: 'Weston', state: 'Florida', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad of N. Fulton Preschool', address: 'Alpharetta, GA', city: 'Alpharetta', state: 'Georgia', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Intown Preschool', address: 'Atlanta, GA', city: 'Atlanta', state: 'Georgia', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Annapolis, MD', city: 'Annapolis', state: 'Maryland', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Baltimore, MD', city: 'Baltimore', state: 'Maryland', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Columbia, MD', city: 'Columbia', state: 'Maryland', country: 'USA', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Newton, MA', city: 'Newton', state: 'Massachusetts', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Ann Arbor, MI', city: 'Ann Arbor', state: 'Michigan', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Las Vegas, NV', city: 'Las Vegas', state: 'Nevada', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Cherry Hill, NJ', city: 'Cherry Hill', state: 'New Jersey', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Toms River, NJ', city: 'Toms River', state: 'New Jersey', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Bay Shore, NY', city: 'Bay Shore', state: 'New York', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Bronx (Riverdale), NY', city: 'Bronx', state: 'New York', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Great Neck, NY', city: 'Great Neck', state: 'New York', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Staten Island, NY', city: 'Staten Island', state: 'New York', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Charlotte, NC', city: 'Charlotte', state: 'North Carolina', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Cincinnati, OH', city: 'Cincinnati', state: 'Ohio', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Bala Cynwyd, PA', city: 'Bala Cynwyd', state: 'Pennsylvania', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Nashville, TN', city: 'Nashville', state: 'Tennessee', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Austin, TX', city: 'Austin', state: 'Texas', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Early Childhood Center', address: 'Dallas, TX', city: 'Dallas', state: 'Texas', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Houston, TX', city: 'Houston', state: 'Texas', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'San Antonio, TX', city: 'San Antonio', state: 'Texas', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Arlington, VA', city: 'Arlington', state: 'Virginia', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Seattle, WA', city: 'Seattle', state: 'Washington', country: 'USA', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Milwaukee, WI', city: 'Milwaukee', state: 'Wisconsin', country: 'USA', category: 'early-childhood' },

  // ===== EARLY CHILDHOOD — INTERNATIONAL =====
  { name: 'Gan Yisroel Early Childhood', address: 'Melbourne, VIC', city: 'Melbourne', state: 'Victoria', country: 'Australia', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Sydney, NSW', city: 'Sydney', state: 'NSW', country: 'Australia', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Vancouver, BC', city: 'Vancouver', state: 'British Columbia', country: 'Canada', category: 'early-childhood' },
  { name: 'Gan Israel Preschool', address: 'Toronto, ON', city: 'Toronto', state: 'Ontario', country: 'Canada', category: 'early-childhood' },
  { name: 'Chabad Preschool', address: 'Montreal, QC', city: 'Montreal', state: 'Quebec', country: 'Canada', category: 'early-childhood' },
  { name: 'Lubavitch Children\'s Center', address: '1 Northfield Rd, London N16 5RL', city: 'London', state: 'London', country: 'United Kingdom', phone: '44-20-8809-9050', email: 'admin@lubavitch.hackney.gov', website: 'www.lubavitchchildrenscentre.com', founded: '2008', category: 'early-childhood' },
  { name: 'Lubavitch Nursery', address: '107-115 Stamford Hill, London N16 5RP', city: 'London', state: 'London', country: 'United Kingdom', founded: '1959', category: 'early-childhood' },
  { name: 'Lubavitch of Edgware Kindergarten', address: '230 Hale Lane, Edgware, Middlesex Ha8 9P2', city: 'Edgware', state: 'London', country: 'United Kingdom', founded: '1979', category: 'early-childhood' },
  { name: 'Leeds Menorah School', address: '399 Street Kane, Leeds LS17 6HQ', city: 'Leeds', state: 'West Yorkshire', country: 'United Kingdom', phone: '44-11-3269-7709', founded: '1978', category: 'early-childhood' },
  { name: 'Torah Montessori Nursery', address: '29 New Church Rd, Brighton, East Sussex BN3 4AD', city: 'Brighton', state: 'East Sussex', country: 'United Kingdom', founded: '1980', category: 'early-childhood' },
  { name: 'Chabad Gannon Eden', address: 'Rudiger Strasse 10, Zurich 8027', city: 'Zurich', state: 'Zurich', country: 'Switzerland', phone: '+41-44-201-0770', founded: '2000', category: 'early-childhood' },
  { name: 'Jewish Preschool Gan Chaja Mushka', address: 'Torild Wulffsgatan 20, Gothenburg 413 19', city: 'Gothenburg', state: '', country: 'Sweden', phone: '46-31-41-33-33', founded: '1992', category: 'early-childhood' },
  { name: 'Torah Academy Preschool', address: 'Chabad Rd, Gallo Manor, Sandton 2052', city: 'Sandton', state: 'Gauteng', country: 'South Africa', founded: '1983', category: 'early-childhood' },
  { name: 'The Sinai Academy Preschool', address: '15 Curlewis Road, Blouberg, Cape Town 7441', city: 'Cape Town', state: 'Western Cape', country: 'South Africa', phone: '021-557-7560', founded: '2006', category: 'early-childhood' },

  // ===== ELEMENTARY — USA =====
  { name: 'Chabad Hebrew Academy', address: 'Phoenix, AZ', city: 'Phoenix', state: 'Arizona', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Torah Day School', address: 'Scottsdale, AZ', city: 'Scottsdale', state: 'Arizona', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Ohr Elchonon Chabad Day School', address: 'Los Angeles, CA', city: 'Los Angeles', state: 'California', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Chabad Day School', address: 'Palo Alto, CA', city: 'Palo Alto', state: 'California', country: 'USA', grades: 'Pre-K\u20135', category: 'elementary' },
  { name: 'Chabad Hebrew Academy', address: 'San Diego, CA', city: 'San Diego', state: 'California', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Southern CT Hebrew Academy', address: 'New Haven, CT', city: 'New Haven', state: 'Connecticut', country: 'USA', grades: 'N\u20138', phone: '203-777-6564', founded: '1965', category: 'elementary' },
  { name: 'Lubavitch Educational Center', address: '1140 Alton Rd, Miami Beach, FL 33139', city: 'Miami Beach', state: 'Florida', country: 'USA', grades: 'N\u201312', phone: '305-653-8770', website: 'www.lecfl.com', founded: '1968', category: 'elementary' },
  { name: 'Chabad Day School', address: 'Boca Raton, FL', city: 'Boca Raton', state: 'Florida', country: 'USA', grades: 'Pre-K\u20135', category: 'elementary' },
  { name: 'Chabad Day School', address: 'Orlando, FL', city: 'Orlando', state: 'Florida', country: 'USA', grades: 'Pre-K\u20135', category: 'elementary' },
  { name: 'South Florida Jewish Academy', address: '3700 Coconut Creek, FL 33066', city: 'Coconut Creek', state: 'Florida', country: 'USA', grades: '9\u201312', phone: '954-427-7788', website: 'www.floridajewishacademy.org', founded: '2007', category: 'elementary' },
  { name: 'Torah Day School of Atlanta', address: 'Atlanta, GA', city: 'Atlanta', state: 'Georgia', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Lubavitch Cheder Day School', address: '6350 North Whipple St, Chicago, IL 60659', city: 'Chicago', state: 'Illinois', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Bais Shalom', address: '331 W. Tilden St, Postville, IA 52162', city: 'Postville', state: 'Iowa', country: 'USA', phone: '563-864-3893', founded: '1997', category: 'elementary' },
  { name: 'Torah Academy', address: 'New Orleans, LA', city: 'New Orleans', state: 'Louisiana', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Shaloh House Day School', address: 'Boston, MA', city: 'Boston', state: 'Massachusetts', country: 'USA', grades: 'Pre-K\u20135', category: 'elementary' },
  { name: 'Yeshiva Beth Yehudah', address: 'Oak Park, MI', city: 'Oak Park', state: 'Michigan', country: 'USA', grades: 'Pre-K\u201312', category: 'elementary' },
  { name: 'Torah Academy', address: 'S. Paul, MN', city: 'St. Paul', state: 'Minnesota', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Desert Torah Academy', address: 'Las Vegas, NV', city: 'Las Vegas', state: 'Nevada', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Beth Rivkah', address: '310 Crown St, Brooklyn, NY 11225', city: 'Brooklyn', state: 'New York', country: 'USA', grades: 'N\u201312', phone: '718-735-0400', website: 'www.bethrivkah.edu', founded: '1942', category: 'elementary' },
  { name: 'Oholei Torah', address: '667 Eastern Parkway, Brooklyn, NY 11213', city: 'Brooklyn', state: 'New York', country: 'USA', grades: 'N\u20138', phone: '718-774-5050', website: 'www.oholeitorah.com', founded: '1956', category: 'elementary' },
  { name: 'Maimonides Hebrew Day School', address: '404 Patridge St, Albany, NY 12208', city: 'Albany', state: 'New York', country: 'USA', grades: 'Pre-K\u20138', phone: '518-495-0779', founded: '1993', category: 'elementary' },
  { name: 'Jewish Institute of Queens', address: '6441 Utopia Parkway, Fresh Meadows, NY 11365', city: 'Fresh Meadows', state: 'New York', country: 'USA', phone: '718-426-9369', website: 'www.jiqueens.com', category: 'elementary' },
  { name: 'Bais Chaya Mushka', address: '27 S. Monsey Rd, Monsey, NY 10952', city: 'Monsey', state: 'New York', country: 'USA', phone: '845-634-7400', website: 'www.monseybcm.com', founded: '2006', category: 'elementary' },
  { name: 'Maimonides Jewish Day School', address: 'Portland, OR', city: 'Portland', state: 'Oregon', country: 'USA', grades: 'K\u20138', category: 'elementary' },
  { name: 'Yeshiva Schools of Pittsburgh', address: 'Pittsburgh, PA', city: 'Pittsburgh', state: 'Pennsylvania', country: 'USA', grades: 'Pre-K\u20138', phone: '412-422-7300', website: 'www.yeshivaschools.com', founded: '1943', category: 'elementary' },
  { name: 'Bais Menachem', address: '148-150 South Franklin St, Wilkes-Barre, PA 18701', city: 'Wilkes-Barre', state: 'Pennsylvania', country: 'USA', phone: '570-970-2480', website: 'www.baismenachem.com', category: 'elementary' },
  { name: 'Torah Day School', address: 'Dallas, TX', city: 'Dallas', state: 'Texas', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Seattle Hebrew Academy', address: 'Seattle, WA', city: 'Seattle', state: 'Washington', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },
  { name: 'Hillel Academy', address: 'Milwaukee, WI', city: 'Milwaukee', state: 'Wisconsin', country: 'USA', grades: 'Pre-K\u20138', category: 'elementary' },

  // ===== ELEMENTARY — INTERNATIONAL =====
  { name: 'Chabad School', address: '18 Connie St, Melbourne, E. Bentleigh 3165', city: 'Melbourne', state: 'Victoria', country: 'Australia', phone: '61-3-9563-8633', founded: '1995', category: 'elementary' },
  { name: 'Beth Rivkah Ladies College', address: '14-20 Balacava Rd, E. St. Kilda, Melbourne, VIC 3183', city: 'Melbourne', state: 'Victoria', country: 'Australia', phone: '61-3-9522-8227', website: 'www.ybr.vic.edu.au', founded: '1956', category: 'elementary' },
  { name: 'Kesser Torah College', address: 'Corner Blake and Napier Streets, Dover Heights, NSW 2030', city: 'Sydney', state: 'NSW', country: 'Australia', phone: '61-2-9301-1111', website: 'www.ktc.nsw.edu.au', category: 'elementary' },
  { name: 'Yeshiva College', address: '88 Hotham St, Kilda East, VIC 3183', city: 'Melbourne', state: 'Victoria', country: 'Australia', phone: '61-3-9528-8330', founded: '1955', category: 'elementary' },
  { name: 'Oholei Torah', address: '1845 Mathers Ave, Winnipeg, Manitoba R3N ON2', city: 'Winnipeg', state: 'Manitoba', country: 'Canada', phone: '204-339-8737', website: 'www.chabadwinnipeg.org', founded: '2007', category: 'elementary' },
  { name: 'Bais Chaya Mushka', address: '4375 Chesswood Dr, Toronto, Ontario M3J 2C2', city: 'Toronto', state: 'Ontario', country: 'Canada', phone: '416-398-9532', website: 'www.bcmschool.ca', founded: '1997', category: 'elementary' },
  { name: 'Cheder Chabad', address: '148 Thornridge Dr, Thornhill, Ontario L4J 1E3', city: 'Thornhill', state: 'Ontario', country: 'Canada', phone: '905-764-8721', category: 'elementary' },
  { name: 'Beth Rivkah Academy', address: '5001 Vezina St, Montreal, Quebec H3W 1C2', city: 'Montreal', state: 'Quebec', country: 'Canada', phone: '514-731-3681', website: 'www.bethrivkah.com', founded: '1956', category: 'elementary' },
  { name: 'Yeshiva Tomchei Temimim - Rabbinical College of Canada', address: '6405 Westbury Ave, Montreal, Quebec H3W 2X5', city: 'Montreal', state: 'Quebec', country: 'Canada', phone: '514-735-2201', website: 'www.yttlmontreal.com', founded: '1942', category: 'elementary' },
  { name: 'Ganeinu International School', address: '262 Grand Hills Beijing, Chaoyang District 100016', city: 'Beijing', state: '', country: 'China', phone: '8610-8470-8238', founded: '2003', category: 'elementary' },
  { name: 'Torah Academy Primary', address: '59 Oaklands Rd, Orchards, Johannesburg 2192', city: 'Johannesburg', state: 'Gauteng', country: 'South Africa', phone: '2711-640-7593', website: 'www.torahacademy.co.za', founded: '1975', category: 'elementary' },
  { name: 'The Sinai Academy', address: '15 Curlewis Rd, Blouberg, Cape Town 7441', city: 'Cape Town', state: 'Western Cape', country: 'South Africa', phone: '021-557-7560', website: 'www.sinaiacademy.co.za', founded: '2006', category: 'elementary' },
  { name: 'Gothenburg\'s Jewish Day School Bais Menachem', address: 'Thorild Wulffsgatan 20, Gothenburg 413 19', city: 'Gothenburg', state: '', country: 'Sweden', phone: '46-31-821-152', website: 'www.chabad.se', founded: '1997', category: 'elementary' },
  { name: 'Lubavitch Junior Boys School', address: '133-135 Clapton Common, London E5 9AE', city: 'London', state: 'London', country: 'United Kingdom', phone: '44-20-8800-1044', website: 'www.lubavitchjuniorboys.com', founded: '1971', category: 'elementary' },
  { name: 'Ruth Lunzer Lubavitch Girls Primary School', address: '107-115 Stamford Hill, London N16 5RP', city: 'London', state: 'London', country: 'United Kingdom', phone: '44-20-8800-0022', founded: '1959', category: 'elementary' },
  { name: 'O.Y.Y. Lubavitch Girls\' School', address: '460 Bury New Rd, Salford, Manchester M7 4LH', city: 'Manchester', state: 'Greater Manchester', country: 'United Kingdom', category: 'elementary' },
  { name: 'Torah Academy', address: '15 The Upper Dr, Hove, East Sussex Bn3 6GR', city: 'Hove', state: 'East Sussex', country: 'United Kingdom', phone: '44-01-22731-8675', website: 'www.lubavitchbrighton.com', category: 'elementary' },

  // ===== HIGH SCHOOLS & MESIVTAS — USA =====
  { name: 'Ohel Chana High School', address: '7659 Beverly Blvd, Los Angeles, CA 90035', city: 'Los Angeles', state: 'California', country: 'USA', grades: '9\u201312', gender: 'girls', phone: '323-954-0900', founded: '1996', category: 'high-school' },
  { name: 'The Hebrew Academy', address: '14401 Willow Lane, Huntington Beach, CA 92647', city: 'Huntington Beach', state: 'California', country: 'USA', phone: '714-898-0051', website: 'www.hebrewacademyhb.com', founded: '1968', category: 'high-school' },
  { name: 'Yeshiva Ohr Elchonon Chabad', address: '7215 Waring Avenue, Los Angeles, CA 90046', city: 'Los Angeles', state: 'California', country: 'USA', phone: '323-937-3763', founded: '1977', category: 'high-school' },
  { name: 'Bais Chana High School for Girls', address: '261 Derby Ave, Orange, CT 06477', city: 'Orange', state: 'Connecticut', country: 'USA', gender: 'girls', phone: '203-795-5261', category: 'high-school' },
  { name: 'Bais Chana Academy (S.C.H.A.)', address: 'New Haven, CT', city: 'New Haven', state: 'Connecticut', country: 'USA', phone: '203-891-9719', website: 'www.schacademy.org', founded: '1965', category: 'high-school' },
  { name: 'Yeshiva Bais Dovid Shlomo', address: '292 Norton Street, New Haven, CT 06511', city: 'New Haven', state: 'Connecticut', country: 'USA', phone: '203-776-9237', website: 'www.ybdsnewhaven.org', category: 'high-school' },
  { name: 'Bais Chana High School', address: '1525 NW 167th St, Suite 115, North Miami Beach, FL 33169', city: 'North Miami Beach', state: 'Florida', country: 'USA', phone: '305-653-8770', website: 'www.lecfl.com', founded: '1968', category: 'high-school' },
  { name: 'Lubavitch Educational Center - Klurman Mesivta HS', address: '1140 Alton Rd, Miami Beach, FL 33139', city: 'Miami Beach', state: 'Florida', country: 'USA', gender: 'boys', phone: '305-673-5664', founded: '1968', category: 'high-school' },
  { name: 'Mesivta of Coral Springs', address: '1730 N. University Dr, Coral Springs, FL 33071', city: 'Coral Springs', state: 'Florida', country: 'USA', gender: 'boys', phone: '954-345-1001', founded: '2007', category: 'high-school' },
  { name: 'Rohr Bais Chaya Academy', address: '8100 N. University Drive, Tamarac, FL 33321', city: 'Tamarac', state: 'Florida', country: 'USA', phone: '954-788-8781', website: 'www.baischaya.com', founded: '2005', category: 'high-school' },
  { name: 'Lubavitch Girls High School', address: '6350 North Whipple St, Chicago, IL 60659', city: 'Chicago', state: 'Illinois', country: 'USA', gender: 'girls', phone: '773-743-7716', website: 'www.lghschicago.org', category: 'high-school' },
  { name: 'Yeshivas Ohr Eliyahu', address: '2756 West Morse Ave, Chicago, IL 60645', city: 'Chicago', state: 'Illinois', country: 'USA', phone: '773-262-0430', website: 'www.lmchicago.org', founded: '1996', category: 'high-school' },
  { name: 'Bais Chaya Mushka', address: '14601 Lincoln St, Oak Park, MI 48237', city: 'Oak Park', state: 'Michigan', country: 'USA', phone: '248-547-0623', website: 'www.cmhighschool.com', category: 'high-school' },
  { name: 'Oholei Yosef Yitzchok Lubavitch Mesivta', address: '15151 W. Ten Mile Rd, Oak Park, MI 48237', city: 'Oak Park', state: 'Michigan', country: 'USA', phone: '248-591-4991', website: 'www.lubavitchcheder.com', category: 'high-school' },
  { name: 'Las Vegas Jewish High', address: '1312 Vista Dr, Las Vegas, NV 89102', city: 'Las Vegas', state: 'Nevada', country: 'USA', phone: '702-259-1000', website: 'www.lvjewishhigh.org', founded: '2012', category: 'high-school' },
  { name: 'Albany Mesivta', address: '404 Patridge St, Albany, NY 12208', city: 'Albany', state: 'New York', country: 'USA', phone: '518-495-0779', founded: '1993', category: 'high-school' },
  { name: 'Aliya Institute', address: '527 E. New York Ave, Brooklyn, NY 11225', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '347-342-9777', website: 'www.aliyahinstitute.com', category: 'high-school' },
  { name: 'Beth Rivkah High School', address: '310 Crown St, Brooklyn, NY 11225', city: 'Brooklyn', state: 'New York', country: 'USA', gender: 'girls', phone: '718-735-0400', website: 'www.bethrivkah.edu', founded: '1942', category: 'high-school' },
  { name: 'Bnos Chomesh Academy', address: '588 Brooklyn Ave, Brooklyn, NY 11203', city: 'Brooklyn', state: 'New York', country: 'USA', gender: 'girls', phone: '718-708-7078', website: 'www.bnoschomesh.com', founded: '2007', category: 'high-school' },
  { name: 'Bnos Menachem School', address: '739 East New York Ave, Brooklyn, NY 11203', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-493-1100', website: 'www.bnosmenachem.org', founded: '1999', category: 'high-school' },
  { name: 'HaMesivta', address: '841-853 Ocean Parkway, Brooklyn, NY 11230', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '347-566-4859', website: 'www.Hamesivta.com', founded: '2005', category: 'high-school' },
  { name: 'Mesivta Oholei Torah', address: '417 Troy ve, Brooklyn, NY 11213', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-363-0019', website: 'www.oholeitorah.com', founded: '1962', category: 'high-school' },
  { name: 'Yeshiva Darchai Menachem', address: '432 Rutland Rd, Brooklyn, NY 11203', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-953-2919', website: 'www.darchaimenachem.com', founded: '2000', category: 'high-school' },
  { name: 'Yeshiva Mesivta Menachem', address: '49 Jackson Ave, Hastings-On-Hudson, NY 10706', city: 'Hastings-On-Hudson', state: 'New York', country: 'USA', phone: '914-274-8777', founded: '2002', category: 'high-school' },
  { name: 'Yeshiva Tomchei Tmimim', address: '885 Eastern Parkway, Brooklyn, NY 11213', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-735-6607', website: 'www.centralyeshiva.com', founded: '1942', category: 'high-school' },
  { name: 'Mesivta Lev Tmimim Lubavitch', address: '17 Blueberry Hill Rd, Monsey, NY 10952', city: 'Monsey', state: 'New York', country: 'USA', phone: '215-825-3745', website: 'www.mesivtamonsey.org', category: 'high-school' },
  { name: 'Monsey Bais Chaya Mushka', address: '27 S. Monsey Rd, Monsey, NY 10952', city: 'Monsey', state: 'New York', country: 'USA', phone: '845-634-7400', website: 'www.monseybcm.com', founded: '2006', category: 'high-school' },
  { name: 'Maimonides Bnos Chaya High School', address: '404 Partridge St, Albany, NY 12208', city: 'Albany', state: 'New York', country: 'USA', gender: 'girls', phone: '518-495-0779', website: 'www.maimonidesschool.org', founded: '1993', category: 'high-school' },
  { name: 'Bais Menachem Youth Development Program', address: '148-150 South Franklin St, Wilkes-Barre, PA 18701', city: 'Wilkes-Barre', state: 'Pennsylvania', country: 'USA', phone: '570-970-2480', website: 'www.baismenachem.com', category: 'high-school' },
  { name: 'Yeshiva Boys\' High School', address: '2100 Wightman St, Pittsburgh, PA 15217', city: 'Pittsburgh', state: 'Pennsylvania', country: 'USA', gender: 'boys', category: 'high-school' },
  { name: 'Yeshiva Girls\' High School', address: '6401 Forbes Ave, Pittsburgh, PA 15217', city: 'Pittsburgh', state: 'Pennsylvania', country: 'USA', gender: 'girls', phone: '412-422-7300', website: 'www.yeshivaschools.com', founded: '1943', category: 'high-school' },
  { name: 'Bader Hillel High - Boys', address: '6789 N. Green Bay Ave, Glendale, WI 53209', city: 'Glendale', state: 'Wisconsin', country: 'USA', gender: 'boys', phone: '414-316-4775', website: 'www.hillelhigh.com', founded: '2013', category: 'high-school' },
  { name: 'Bader Hillel High - Girls', address: '6789 N. Green Bay Ave, Glendale, WI 53209', city: 'Glendale', state: 'Wisconsin', country: 'USA', gender: 'girls', phone: '414-316-4775', website: 'www.hillelhigh.com', founded: '2013', category: 'high-school' },

  // ===== HIGH SCHOOLS — INTERNATIONAL =====
  { name: 'Beth Rivkah Ladies\' College (HS)', address: '14-20 Balaclava Rd, Melbourne, VIC 3183', city: 'Melbourne', state: 'Victoria', country: 'Australia', phone: '61-3-9522-8229', website: 'www.ybr.vic.edu.au', founded: '1956', category: 'high-school' },
  { name: 'Yeshivah College High School', address: '88 Hotham St, Melbourne, VIC 3183', city: 'Melbourne', state: 'Victoria', country: 'Australia', phone: '61-3-9522-8223', website: 'www.ybr.vic.edu.au', founded: '1955', category: 'high-school' },
  { name: 'Kesser Torah College - Boys', address: 'Corner Blake and Napier Streets, Dover Heights, NSW 2030', city: 'Sydney', state: 'NSW', country: 'Australia', phone: '61-2-9301-1111', website: 'www.kessertorah.nsw.edu.au', category: 'high-school' },
  { name: 'Kesser Torah College - Girls', address: 'Corner Blake and Napier Streets, Dover Heights, NSW 2030', city: 'Sydney', state: 'NSW', country: 'Australia', phone: '61-2-9301-1111', website: 'www.kessertorah.nsw.edu.au', category: 'high-school' },
  { name: 'Bais Chomesh High School for Girls', address: '3600 Bathurst St, North York, Ontario M6A 2C9', city: 'Toronto', state: 'Ontario', country: 'Canada', phone: '416-631-0585', founded: '1999', category: 'high-school' },
  { name: 'Mesivta Ohr Temimim Lubavitch', address: '78 Theodore Place, Thornhill, Ontario L4J 8E4', city: 'Thornhill', state: 'Ontario', country: 'Canada', phone: '647-999-2456', website: 'www.ohrtemimim.com', founded: '2015', category: 'high-school' },
  { name: 'Yeshivas Lubavitch Toronto', address: '3055 Bathurst St, Toronto, Ontario M6B 3B7', city: 'Toronto', state: 'Ontario', country: 'Canada', phone: '416-787-6631', website: 'www.lubavitchyeshiva.com', founded: '1996', category: 'high-school' },
  { name: 'Beth Rivkah Academy (HS)', address: '5001 Vezina St, Montreal, Quebec H3W 1C2', city: 'Montreal', state: 'Quebec', country: 'Canada', phone: '514-731-3681', website: 'www.bethrivkah.com', category: 'high-school' },
  { name: 'Mesivta Kerem Menachem', address: '6253 Westbury Ave, Montreal, Quebec H3W 2X4', city: 'Montreal', state: 'Quebec', country: 'Canada', phone: '514-225-5122', website: 'www.mesivtakeremmenachem.com', category: 'high-school' },
  { name: 'Yeshiva Or Menachem', address: '23 doble Rang, Napierville, Quebec J0J 1L0', city: 'Napierville', state: 'Quebec', country: 'Canada', phone: '514-341-1770', website: 'www.ormenachem.com', founded: '2003', category: 'high-school' },
  { name: 'Yeshivas Bais Menachem Mendel', address: "R'chov Hagdud Hashlishi 5, Tzfat 13410", city: 'Tzfat', state: '', country: 'Israel', phone: '972-52-709-7974', website: 'www.youngshluchim.com', category: 'high-school' },
  { name: 'Torah Academy Boys\' High', address: '59 Oaklands Rd, Orchards, Johannesburg 2192', city: 'Johannesburg', state: 'Gauteng', country: 'South Africa', phone: '271-1640-7566', website: 'www.torahacademy.co.za', founded: '1975', category: 'high-school' },
  { name: 'Torah Academy Girls\' High', address: '59 Oaklands Rd, Orchards, Johannesburg 2192', city: 'Johannesburg', state: 'Gauteng', country: 'South Africa', phone: '271-1640-2975', website: 'www.torahacademy.co.za', founded: '1975', category: 'high-school' },
  { name: 'OYY Lubavitch Girls\' School (HS)', address: '460 Bury New Road, Salford, Manchester M7 4LH', city: 'Manchester', state: 'Greater Manchester', country: 'United Kingdom', phone: '44-161-705-0483', founded: '1980', category: 'high-school' },
  { name: 'Leeds Jewish High School for Girls', address: '2 Sand Hill Lane, Leeds LS17 6AQ', city: 'Leeds', state: 'West Yorkshire', country: 'United Kingdom', phone: '44-776-230-0101', founded: '1998', category: 'high-school' },
  { name: 'Lubavitch Mechinah L\'Yeshiva', address: '1117 Finchley Rd, London NW11 0QB', city: 'London', state: 'London', country: 'United Kingdom', phone: '44-20-3409-1853', founded: '1972', category: 'high-school' },
  { name: 'Lubavitch Senior Girls\' School', address: '107-115 Stamford Hill, London N16 5RP', city: 'London', state: 'London', country: 'United Kingdom', category: 'high-school' },
  { name: 'Lubavitch Yeshiva Manchester', address: '62 Singleton Rd, Manchester M7 OLU', city: 'Manchester', state: 'Greater Manchester', country: 'United Kingdom', phone: '44-161-740-4243', category: 'high-school' },

  // ===== SEMINARIES =====
  { name: 'Merkos Women\'s Seminary', address: '10 Springfield Ave, E. St. Kilda, Melbourne, VIC 3108', city: 'Melbourne', state: 'Victoria', country: 'Australia', category: 'seminary' },
  { name: 'Ohel Chana Werdiger Learning Institute', address: '88 Hotham Street, E. St. Kilda, VIC 3183', city: 'Melbourne', state: 'Victoria', country: 'Australia', phone: '61-3-9522-8258', website: 'www.ohelchana.edu.au', founded: '1971', category: 'seminary' },
  { name: 'Beis Moshe Chaim', address: '33 S. Vincent S. Agathe, Quebec J8C 2A5', city: 'Ste. Agathe', state: 'Quebec', country: 'Canada', phone: '819-321-1111', website: 'www.SeminaryBMC.org', category: 'seminary' },
  { name: 'Chaya Mushka Seminary', address: '5115 Vezina St, Montreal, Quebec H3W 1C2', city: 'Montreal', state: 'Quebec', country: 'Canada', phone: '514-733-2221', website: 'www.chayamushkaseminary.com', founded: '1988', category: 'seminary' },
  { name: 'Chaya Aydel Seminary', address: '1295 East Hallandale Beach Blvd, Hallandale Beach, FL 33009', city: 'Hallandale Beach', state: 'Florida', country: 'USA', phone: '954-458-1877', website: 'www.chayaaydelsem.com', founded: '2002', category: 'seminary' },
  { name: 'Bais Chaya Mushka and Machon Alte Seminary', address: 'Jerusalem St. 33, Tzfat 13100', city: 'Tzfat', state: '', country: 'Israel', phone: '972-4-697-4306', website: 'www.machonalte.com', category: 'seminary' },
  { name: 'Beit Chana Seminary', address: 'Kiryat Chabad, Tzfat 13410', city: 'Tzfat', state: '', country: 'Israel', phone: '972-73-255-0370', website: 'www.beitchana.org', category: 'seminary' },
  { name: 'Machon Shoshanat Yerushalayim', address: 'Admur Milubavitch 41, Jerusalem 91058', city: 'Jerusalem', state: '', country: 'Israel', phone: '972-2-587-1711', website: 'www.msy.org.il', founded: '1999', category: 'seminary' },
  { name: 'Pnimiyut Seminary', address: '45 Rechov Chaim Levanon, Tel Aviv 69975', city: 'Tel Aviv', state: '', country: 'Israel', phone: '972-3-643-6895', founded: '2007', category: 'seminary' },
  { name: 'Beis Chana Seminary', address: 'Via Carlo Poerio 35, Milan 20129', city: 'Milan', state: '', country: 'Italy', phone: '390-22-953-1213', founded: '2006', category: 'seminary' },
  { name: 'Associated Beth Rivkah Schools - Division of Higher Learning', address: '310 Crown St, Brooklyn, NY 11225', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-735-0400', website: 'www.dhl.bethrivkah.edu', category: 'seminary' },
  { name: 'Machon Chana', address: '556 Crown St, Brooklyn, NY 11213', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-735-0030', website: 'www.machonchana.org', founded: '1970', category: 'seminary' },
  { name: 'Tzohar Seminary for Chassidus and the Arts', address: '6404 Forbes Ave, Pittsburgh, PA 15217', city: 'Pittsburgh', state: 'Pennsylvania', country: 'USA', phone: '412-521-1197', website: 'www.tzoharseminary.com', category: 'seminary' },

  // ===== YESHIVOS GEDOLOS =====
  { name: 'Rabbinical College of Australia and New Zealand', address: '67 Alexandra Street, East St. Kilda, VIC 3183', city: 'Melbourne', state: 'Victoria', country: 'Australia', phone: '61-3-9525-9165', website: 'www.rabbinicalcollege.edu.au', founded: '1966', category: 'yeshiva-gedolah' },
  { name: 'Yeshiva Gedolah Rabbinical College', address: '36 Flood Street, Bondi, NSW 2026', city: 'Sydney', state: 'NSW', country: 'Australia', phone: '02-8091-5770', website: 'www.yeshiva.org.au', category: 'yeshiva-gedolah' },
  { name: 'Yeshiva Ohr Elchonon Chabad (Gedolah)', address: '7215 Waring Ave, Los Angeles, CA 90046', city: 'Los Angeles', state: 'California', country: 'USA', phone: '323-937-3763', website: 'www.yoec.edu', founded: '1977', category: 'yeshiva-gedolah' },
  { name: 'Rabbinical College of Quebec - Tomchei Tmimim Lubavitch Bais Medrash', address: '6355 Westbury Ave, Montreal, Quebec H3W 1G7', city: 'Montreal', state: 'Quebec', country: 'Canada', phone: '514-227-7770', website: 'www.rabbinicalcollege.ca', founded: '1942', category: 'yeshiva-gedolah' },
  { name: 'Yeshiva Gedolah Miami', address: '1140 Alton Rd, Miami Beach, FL 33139', city: 'Miami Beach', state: 'Florida', country: 'USA', phone: '305-673-5664', website: 'www.lecfl.com/about-yeshiva-gedolah', founded: '1974', category: 'yeshiva-gedolah' },
  { name: 'Bais Shalom (Yeshiva Gedolah)', address: '331 Tilden Street, Postville, IA 52162', city: 'Postville', state: 'Iowa', country: 'USA', phone: '563-864-3893', website: 'www.mesivtapostville.org', founded: '1997', category: 'yeshiva-gedolah' },
  { name: 'Yeshivas Lubavitch Baltimore', address: '6702 Parks Heights Ave, Baltimore, MD 21215', city: 'Baltimore', state: 'Maryland', country: 'USA', phone: '410-205-5031', website: 'www.yeshivaslubavitchbaltimore.com', founded: '2005', category: 'yeshiva-gedolah' },
  { name: 'Yeshivas Menachem Mendel Lubavitch', address: '15151 W. Ten Mile Rd, Oak Park, MI 48237', city: 'Oak Park', state: 'Michigan', country: 'USA', phone: '248-591-4994', category: 'yeshiva-gedolah' },
  { name: 'Yeshivas Tomchei Tmimim (Rabbinical College of America)', address: '226 Sussex Ave, Morristown, NJ 07960', city: 'Morristown', state: 'New Jersey', country: 'USA', phone: '973-267-9404', website: 'www.rca.edu', founded: '1958', category: 'yeshiva-gedolah' },
  { name: 'Central Yeshiva Tomchei Tmimim Lubavitch — 770', address: '770 Eastern Parkway, Brooklyn, NY 11213', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-859-7600', founded: '1940', category: 'yeshiva-gedolah' },
  { name: 'Hadar HaTorah Rabbinical Seminary', address: '824 Eastern Parkway, Brooklyn, NY 11213', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-735-0250', website: 'www.hadarhatorah.org', founded: '1966', category: 'yeshiva-gedolah' },
  { name: 'Talmudical Seminary Oholei Torah', address: '668 Eastern Parkway, Brooklyn, NY 11213', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-774-5050', website: 'www.oholeitorah.com', founded: '1970', category: 'yeshiva-gedolah' },
  { name: 'Yeshivas Tomchei Tmimim Lubavitch Chovevei Torah', address: '885 Eastern Parkway, Brooklyn, NY 11213', city: 'Brooklyn', state: 'New York', country: 'USA', phone: '718-735-6607', website: 'www.centralyeshiva.com', founded: '1942', category: 'yeshiva-gedolah' },
  { name: 'Yeshiva Gedolah Lubavitch', address: '3-5 Kingsley Way, London N2 0EH', city: 'London', state: 'London', country: 'United Kingdom', phone: '44-181-458-2312', website: 'www.yeshivalondon.com', founded: '1982', category: 'yeshiva-gedolah' },
  { name: 'Yeshivas Lubavitch Manchester', address: '62 Singleton Rd, Salford, Lancashire M7 4LU', city: 'Manchester', state: 'Greater Manchester', country: 'United Kingdom', phone: '44-161-740-4243', founded: '1982', category: 'yeshiva-gedolah' },
];
